### ISSUE TITLE
Permisos app

### ISSUE THREAD

**Issue by Yayo-Arellano** [NopalDesignAndSoftware/Nucleo-Web#104]
Necesito saber que tipos de permiso puede tener cada usuario (adminitrador, maestro, alumno, otros). Esto para poder mostrar u ocultar opciones dentro de la app.Mi idea es cuando el usuario inicie sesion regresar una lista con todos los posibles permisos y si el usuario puede acceder a ellos ponerlo en true en caso contrario en false de esta forma podemos cambiar la funcionalidad de la app sin necesidad de actualizar la app en la appstore.
Ejemplo:
Llamamos la api login
https://github.com/NopalDesignAndSoftware/Nucleo-Web/wiki/API#get-personaslogin
Y nos regresa:
```
{
    "id_persona": "int",
    "matricula": "string",
    "nombres": "string",
    "apellido_paterno": "string",
    "apellido_materno": "string",
    "password": "string",
    "tipo_persona": "int",
    "fecha_alta": "fecha",
    "fecha_baja": "fecha",
    "foto": "string",
    "sexo": "string",
    "permisos": {
        "ESTADISTICAS": "false",
        "READ_CICLOS": "false",
        "WRITE_CICLOS": "false",
        "READ_ALUMNOS": "false",
        "WRITE_ALUMNOS": "false",
        "READ_MAESTROS": "false",
        "WRITE_MAESTROS": "false",
        "READ_ADMINISTRADORES": "false",
        "WRITE_ADMINISTRADORES": "false"
    }
}
```

ESTADISTICAS: Permite al usuario ver las estadisticas
READ_CICLOS: Permite ver las estadisticas
WRITE_CICLOS: Permite crear ciclos nuevos
READ_ALUMNOS: Permite ver el listado de los alumnos y sus detalles
WRITE_ALUMNOS: Permite editar los alumnos asi como crear nuevos alumnos
READ_MAESTROS: Permite ver el listado de maestros y sus detalles
WRITE_MAESTROS: Permite editar los maestros asi como crear nuevos maestros
READ_ADMINISTRADORES: Permite ver el listado de los administradores
WRITE_ADMINISTRADORES: Permite editar los adminitradores asi como crear nuevos

**Comment by Yozki** [comment]
Que tal Yayo, le quiero dar a esto pero creo que seria mejor mantener hardcodeado los permisos, porque todos los alumnos tendrán acceso a los mismos modulos siempre, todos los admins a los mismos modulos, etc.

Osea 2 administradores distintos nunca tendrán acceso a módulos diferentes, por lo que sugiero mejor crear una lista en el wiki con los módulos a los que cada usuario tiene acceso, y tu hardcodear en tu app si el usuario tiene acceso a X modulo, basandote en su tipo de usuario (Alumno, docente o administrador) 

Que opinas?
