### ISSUE TITLE
lista de pagos realizados con dicho concepto del ciclo actual (Con total)

### ISSUE THREAD

**Issue by Yozki** [NopalDesignAndSoftware/Nucleo-Web#61]
lista de pagos realizados con dicho concepto del ciclo actual (Con total) http://ift.tt/1D5rB4w<br><br>
Prioridad: Priority 1<br>
Creada: January 27, 2015 at 03:20PM

**Comment by CesRmz** [comment]
Página de Detalles de Conceptos creada .. faltaría agregar las funciones extras para esta página.
