### ISSUE TITLE
Estadisticas (get)

### ISSUE THREAD

**Issue by Yayo-Arellano** [NopalDesignAndSoftware/Nucleo-Web#90]
Enviar las datos que se van a mostrar en la aplicacion. Separar como en la pagina web

**Comment by Yozki** [comment]
Los mismos datos que en web?

**Comment by Yayo-Arellano** [comment]
Si los mismos datos, aqui voy a armar las graficas con una libreria

**Comment by Yozki** [comment]
https://github.com/NopalDesignAndSoftware/Nucleo-Web/wiki/API#get-estadisticasalumnos

Checa si te sirve eso, mi plan es dejar esa llamada (estadisticas/alumnos) que regrese las 3 estadisticas, y además crear 3 llamadas adicionales mas específicas:

estadisticas/alumnos/distribucion
estadisticas/alumnos/inscripciones
estadisticas/alumnos/inscritos

What do you think?

**Comment by Yayo-Arellano** [comment]
Mañana empiezo a trabajar con eso y te digo porque tengo que ver como voy a armar las graficas

**Comment by Yayo-Arellano** [comment]
Ya quedo bien. Tambien hay que hacer las estadisticas de maestros, clubs, etc.

**Comment by Yozki** [comment]
Estadisticas/docentes ya quedó
