### ISSUE TITLE
Formato de las imagenes

### ISSUE THREAD

**Issue by Yayo-Arellano** [NopalDesignAndSoftware/Nucleo-Web#91]
En el web API /personas/login Algunas imagenes regresan un formato que no es soportado por algunas versiones de Android. 
El problema no es que sean .jpg, png, etc. sino el modelo de color o ImageColorSpace( 
Ex: CMKY, RGB, Multichannel, etc)

Para asegurar la compatibilidad en la mayoria de los dispositos lo ideal es que sea RGB.
Lo ideal es que el servidor no permita subir imagenes que no tengan el formato adecuedo.. Aqui entonctre allgo de info en PHP que tal vez te pueda ayudar

http://php.net/manual/en/imagick.getcolorspace.php
http://php.net/manual/en/imagick.setimagecolorspace.php

**Comment by Yozki** [comment]
Ok, en la tarde lo reviso
